export const designTokens = {
  colors: {
    paper: "oklch(.965 .008 250)",
    paperRaised: "oklch(.995 .004 250)",
    paperMuted: "oklch(.975 .007 250)",
    ink: "oklch(.25 .02 250)",
    inkMuted: "oklch(.48 .018 250)",
    inkFaint: "oklch(.59 .014 250)",
    rule: "oklch(.87 .012 250)",
    ruleStrong: "oklch(.74 .02 250)",
    accent: "oklch(.48 .16 252)",
    accentInk: "oklch(.99 .004 250)",
    accentSoft: "oklch(.94 .03 252)",
    income: "oklch(.45 .12 155)",
    expense: "oklch(.48 .15 28)",
    danger: "oklch(.5 .17 28)",
    sidebar: "oklch(.25 .02 250)",
    sidebarRaised: "oklch(.31 .025 250)",
    sidebarLink: "oklch(.86 .02 250)",
    sidebarCurrentRule: "oklch(.72 .13 252)",
    detailShadow: "oklch(.25 .02 250/.12)",
  },
  space: {
    one: 4,
    two: 8,
    three: 12,
    four: 16,
    five: 20,
    six: 24,
    eight: 32,
  },
  radius: {
    one: 3,
    two: 5,
  },
  typography: {
    body: "Noto Sans SC",
    mono: "IBM Plex Mono",
  },
  motion: {
    fast: 120,
    panel: 160,
  },
  touchTarget: 44,
} as const;

export const nativeColors = {
  paper: "#F1F5FA",
  paperRaised: "#FCFDFE",
  paperMuted: "#E8EEF6",
  ink: "#1F2933",
  inkMuted: "#66717D",
  inkFaint: "#8B98A8",
  rule: "#C4CEDA",
  ruleStrong: "#9EACBC",
  accent: "#0A63B8",
  accentInk: "#FFFFFF",
  accentSoft: "#E0ECFB",
  income: "#087443",
  expense: "#B3442C",
  danger: "#B42318",
  errorSurface: "#FBEAE8",
  successSurface: "#E8F5EE",
  sidebar: "#1F2933",
  sidebarRaised: "#303B48",
  sidebarLink: "#D6E0EB",
  sidebarCurrentRule: "#4C9AF0",
} as const;

export const nativeTypography = {
  mono: "monospace",
} as const;

export const cssVariableMap = {
  "--color-paper": designTokens.colors.paper,
  "--color-paper-raised": designTokens.colors.paperRaised,
  "--color-paper-muted": designTokens.colors.paperMuted,
  "--color-ink": designTokens.colors.ink,
  "--color-ink-muted": designTokens.colors.inkMuted,
  "--color-ink-faint": designTokens.colors.inkFaint,
  "--color-rule": designTokens.colors.rule,
  "--color-rule-strong": designTokens.colors.ruleStrong,
  "--color-accent": designTokens.colors.accent,
  "--color-accent-ink": designTokens.colors.accentInk,
  "--color-accent-soft": designTokens.colors.accentSoft,
  "--color-income": designTokens.colors.income,
  "--color-expense": designTokens.colors.expense,
  "--color-danger": designTokens.colors.danger,
  "--color-sidebar": designTokens.colors.sidebar,
  "--color-sidebar-raised": designTokens.colors.sidebarRaised,
  "--color-sidebar-link": designTokens.colors.sidebarLink,
  "--color-sidebar-current-rule": designTokens.colors.sidebarCurrentRule,
  "--color-detail-shadow": designTokens.colors.detailShadow,
  "--font-body": `"${designTokens.typography.body}", sans-serif`,
  "--font-mono": `"${designTokens.typography.mono}", monospace`,
  "--space-1": `${designTokens.space.one}px`,
  "--space-2": `${designTokens.space.two}px`,
  "--space-3": `${designTokens.space.three}px`,
  "--space-4": `${designTokens.space.four}px`,
  "--space-5": `${designTokens.space.five}px`,
  "--space-6": `${designTokens.space.six}px`,
  "--space-8": `${designTokens.space.eight}px`,
  "--radius-1": `${designTokens.radius.one}px`,
  "--radius-2": `${designTokens.radius.two}px`,
  "--dur-fast": `${designTokens.motion.fast}ms`,
  "--dur-panel": `${designTokens.motion.panel}ms`,
} as const;
