// Generated by scripts/generate_ui_tokens.py; do not edit by hand.
package com.finance.tracker.core.design

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object GeneratedTokens {
    object Core {
        object Color {
            val BrandOnPrimary = Color(0xFFFFFFFF)
            val BrandPrimary = Color(0xFF0A63B8)
            val SemanticAccent = Color(0xFF0485F7)
            val SemanticAccentForeground = Color(0xFFFFFFFF)
            val SemanticDanger = Color(0xFFB42318)
            val SemanticExpense = Color(0xFFB3442C)
            val SemanticIncome = Color(0xFF087443)
        }
        object Control {
            val MinTouchTarget = 44.dp
        }
        object Font {
            val FamilyBody = "Noto Sans SC"
            val FamilyMono = "IBM Plex Mono"
        }
        object Layout {
            val FormMaxWidth = 720.dp
            val RegularMinWidth = 600
            val WideMinWidth = 1024
        }
        object Radius {
            val Token1 = 3.dp
            val Token2 = 5.dp
        }
        object Space {
            val Token1 = 4.dp
            val Token2 = 8.dp
            val Token3 = 12.dp
            val Token4 = 16.dp
            val Token5 = 20.dp
            val Token6 = 24.dp
            val Token8 = 32.dp
        }
    }
    object Dark {
        object Color {
            val BorderDefault = Color(0xFF3F3F46)
            val ContentMuted = Color(0xFFA1A1AA)
            val ContentPrimary = Color(0xFFFCFCFC)
            val SemanticBackground = Color(0xFF060607)
            val SemanticDanger = Color(0xFFF04438)
            val SemanticDisabled = Color(0xFF27272A)
            val SemanticField = Color(0xFF18181B)
            val SemanticFieldBorder = Color(0xFF3F3F46)
            val SemanticFocus = Color(0xFF0485F7)
            val SemanticForeground = Color(0xFFFCFCFC)
            val SemanticOverlay = Color(0xFF18181B)
            val SemanticSurface = Color(0xFF18181B)
            val StateErrorSurface = Color(0xFF93000A)
            val StateSuccessSurface = Color(0xFF1C4A35)
            val SurfaceBackground = Color(0xFF060607)
            val SurfaceMuted = Color(0xFF27272A)
            val SurfaceRaised = Color(0xFF18181B)
        }
    }
    object Light {
        object Color {
            val BorderDefault = Color(0xFFE4E4E7)
            val ContentMuted = Color(0xFF71717A)
            val ContentPrimary = Color(0xFF18181B)
            val SemanticBackground = Color(0xFFF5F5F5)
            val SemanticDisabled = Color(0xFFE4E4E7)
            val SemanticField = Color(0xFFFFFFFF)
            val SemanticFieldBorder = Color(0xFFE4E4E7)
            val SemanticFocus = Color(0xFF0485F7)
            val SemanticForeground = Color(0xFF18181B)
            val SemanticOverlay = Color(0xFFFFFFFF)
            val SemanticSurface = Color(0xFFFFFFFF)
            val StateErrorSurface = Color(0xFFFBEAE8)
            val StateSuccessSurface = Color(0xFFE8F5EE)
            val SurfaceBackground = Color(0xFFF5F5F5)
            val SurfaceMuted = Color(0xFFE4E4E7)
            val SurfaceRaised = Color(0xFFFFFFFF)
        }
    }
}
