// Generated by scripts/generate_ui_tokens.py; do not edit by hand.
package com.finance.tracker.core.design

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object GeneratedTokens {
    object Core {
        object Color {
            val BrandOnPrimary = Color(0xFFFFFFFF)
            val BrandPrimary = Color(0xFF0A63B8)
            val SemanticDanger = Color(0xFFB42318)
            val SemanticExpense = Color(0xFFB3442C)
            val SemanticIncome = Color(0xFF087443)
        }
        object Control {
            val MinTouchTarget = 44.dp
        }
        object Font {
            val FamilyBody = "Noto Sans SC"
            val FamilyMono = "IBM Plex Mono"
        }
        object Layout {
            val FormMaxWidth = 720.dp
            val RegularMinWidth = 600
            val WideMinWidth = 1024
        }
        object Radius {
            val Token1 = 3.dp
            val Token2 = 5.dp
        }
        object Space {
            val Token1 = 4.dp
            val Token2 = 8.dp
            val Token3 = 12.dp
            val Token4 = 16.dp
            val Token5 = 20.dp
            val Token6 = 24.dp
            val Token8 = 32.dp
        }
    }
    object Dark {
        object Color {
            val BorderDefault = Color(0xFF434850)
            val ContentMuted = Color(0xFFC3C7D0)
            val ContentPrimary = Color(0xFFE2E2E9)
            val StateErrorSurface = Color(0xFF93000A)
            val StateSuccessSurface = Color(0xFF1C4A35)
            val SurfaceBackground = Color(0xFF111318)
            val SurfaceMuted = Color(0xFF2B2F38)
            val SurfaceRaised = Color(0xFF1B1D24)
        }
    }
    object Light {
        object Color {
            val BorderDefault = Color(0xFFC4CEDA)
            val ContentMuted = Color(0xFF66717D)
            val ContentPrimary = Color(0xFF1F2933)
            val StateErrorSurface = Color(0xFFFBEAE8)
            val StateSuccessSurface = Color(0xFFE8F5EE)
            val SurfaceBackground = Color(0xFFF1F5FA)
            val SurfaceMuted = Color(0xFFE8EEF6)
            val SurfaceRaised = Color(0xFFFCFDFE)
        }
    }
}
