#!/usr/bin/env python3
"""Generate stable Compose token code and a pen.dev variable manifest."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TOKEN_DIR = ROOT / "openspec" / "specs" / "shared" / "design-system" / "tokens"
KOTLIN_OUT = ROOT / "compose" / "shared" / "src" / "commonMain" / "kotlin" / "com" / "finance" / "tracker" / "core" / "design" / "GeneratedTokens.kt"
PEN_OUT = ROOT / "design" / "generated" / "pen-variables.json"


def pascal(value: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", value)
    result = "".join(part[:1].upper() + part[1:] for part in parts if part)
    return f"Token{result}" if result and result[0].isdigit() else result


def kotlin_value(token_type: str, value: object) -> str:
    if token_type == "color":
        raw = str(value).removeprefix("#")
        if len(raw) == 6:
            raw = "FF" + raw
        return f"Color(0x{raw.upper()})"
    if token_type == "dimension":
        return f"{str(value).removesuffix('px')}.dp"
    if token_type == "number":
        return str(value)
    return json.dumps(value, ensure_ascii=True)


def load_tokens() -> dict[str, dict[str, object]]:
    merged: dict[str, dict[str, object]] = {}
    for path in sorted(TOKEN_DIR.glob("*.tokens.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        for name, token in payload["tokens"].items():
            entry = dict(token)
            entry["source"] = path.name
            merged[f"{path.stem.removesuffix('.tokens')}.{name}"] = entry
    return dict(sorted(merged.items()))


def generate() -> None:
    tokens = load_tokens()
    grouped: dict[str, dict[str, list[tuple[str, dict[str, object]]]]] = {}
    for name, token in tokens.items():
        mode, remainder = name.split(".", 1)
        group, key = remainder.split(".", 1)
        grouped.setdefault(mode, {}).setdefault(group, []).append((key, token))

    lines = [
        "// Generated by scripts/generate_ui_tokens.py; do not edit by hand.",
        "package com.finance.tracker.core.design",
        "",
        "import androidx.compose.ui.graphics.Color",
        "import androidx.compose.ui.unit.dp",
        "",
        "object GeneratedTokens {",
    ]
    for mode in sorted(grouped):
        lines.append(f"    object {pascal(mode)} {{")
        for group in sorted(grouped[mode]):
            lines.append(f"        object {pascal(group)} {{")
            for key, token in grouped[mode][group]:
                lines.append(f"            val {pascal(key)} = {kotlin_value(token['type'], token['value'])}")
            lines.append("        }")
        lines.append("    }")
    lines.append("}")
    lines.append("")
    KOTLIN_OUT.parent.mkdir(parents=True, exist_ok=True)
    KOTLIN_OUT.write_text("\n".join(lines), encoding="utf-8")

    PEN_OUT.parent.mkdir(parents=True, exist_ok=True)
    PEN_OUT.write_text(
        json.dumps(
            {
                "source": "openspec/specs/shared/design-system/tokens/*.tokens.json",
                "variables": [
                    {"name": name, "type": token["type"], "value": token["value"], "source": token["source"]}
                    for name, token in tokens.items()
                ],
            },
            indent=2,
            ensure_ascii=True,
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    generate()
