package com.finance.tracker.presentation

import com.finance.tracker.domain.*

data class CashLedgerUiState(
    val accounts: List<Account> = emptyList(),
    val categories: List<CashCategory> = emptyList(),
    val options: LedgerOptions = LedgerOptions(),
    val page: CashPage? = null,
    val filterOptions: CashFilterOptions = CashFilterOptions(),
    val rows: List<CashProjection> = emptyList(),
    val nextCursor: String? = null,
    val projectionVersion: Long = 0,
    val loading: Boolean = true,
    val loadingMore: Boolean = false,
    val appendErrorCode: String? = null,
    val errorCode: String? = null,
    val referencesErrorCode: String? = null,
    val filters: CashFilters = CashFilters(),
    val selectedIds: Set<String> = emptySet(),
    val selectedCategory: String = "",
    val classifyBusy: Boolean = false,
    val classifyErrorCode: String? = null,
    val deleteProjectionImpact: CashProjectionDeleteImpact? = null,
    val deleteProjectionBusy: Boolean = false,
    val deleteProjectionErrorCode: String? = null,
    val selectedRow: CashProjection? = null,
    val evidence: Evidence? = null,
    val recordDetail: CashRecordDetail? = null,
    val recordLoading: Boolean = false,
    val recordErrorCode: String? = null,
    val recordDraft: CashRecordDraft? = null,
    val recordBusy: Boolean = false,
    val recordSaveErrorCode: String? = null,
    val confirmRelationImpact: Boolean = false,
    val relationComposerOpen: Boolean = false,
    val relationQuery: String = "",
    val relationCandidates: List<CashRecord> = emptyList(),
    val relationType: String = "payment_mirror",
    val relationDateFrom: String = "",
    val relationDateTo: String = "",
    val relationNextCursor: String? = null,
    val relationPageNumber: Int = 1,
    val relationPageStarts: List<String?> = listOf(null),
    val relationLoadError: Boolean = false,
    val relationErrorPage: Int? = null,
    val relationErrorCursor: String? = null,
    val relationTarget: String? = null,
    val relationBusy: Boolean = false,
    val editingRelationId: String? = null,
    val editingRelationKind: String? = null,
    val detailActionErrorCode: String? = null,
    val deleteRecordConfirm: Boolean = false,
    val deleteRecordBusy: Boolean = false,
)

data class CashRecordDraft(
    val id: String? = null,
    val originalCategoryId: String? = null,
    val occurredAt: String = "",
    val amount: String = "",
    val currency: String = "CNY",
    val counterparty: String = "",
    val counterpartyAccount: String = "",
    val note: String = "",
    val accountName: String = "",
    val recordType: String = "",
    val recordSubtype: String = "not_applicable",
    val categoryId: String? = null,
    val projectionVersion: Long? = null,
) {
    fun toWrite(confirmRelationImpact: Boolean): CashRecordWrite = CashRecordWrite(
        occurredAt = occurredAt,
        amount = amount,
        currency = currency,
        counterparty = counterparty,
        counterpartyAccount = counterpartyAccount,
        note = note,
        accountName = accountName,
        recordType = recordType,
        recordSubtype = recordSubtype,
        categoryId = categoryId,
        projectionVersion = projectionVersion.takeIf { id != null && categoryId != originalCategoryId },
        confirmRelationImpact = true.takeIf { confirmRelationImpact },
    )
}
